# Generated by Django 4.1.6 on 2023-02-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
