# Generated by Django 4.1.6 on 2023-02-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0002_remove_profile_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('interested', models.ManyToManyField(related_name='profile_interested', to='sustainabilityapp.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainabilityapp.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='owner',
        ),
        migrations.DeleteModel(
            name='DonationPost',
        ),
        migrations.DeleteModel(
            name='EventPost',
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainabilityapp.post'),
        ),
    ]
