# Generated by Django 4.1.6 on 2023-02-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0004_alter_post_interested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainabilityapp.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainabilityapp.post')),
            ],
        ),
    ]
