# Generated by Django 4.1.6 on 2023-02-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='sustainabilityapp.tags'),
        ),
    ]
