# Generated by Django 4.1.6 on 2023-02-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0006_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interested',
            field=models.ManyToManyField(null=True, related_name='interested', to='sustainabilityapp.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags', to='sustainabilityapp.tags'),
        ),
    ]
